### ISSUE TITLE
Server crash on Chunk load

### ISSUE THREAD

**Issue by CommanderLouiz** [OpenModularTurretsTeam/OpenModularPassiveDefense#28] opened 2019-12-06 19:44 UTC
[crash-2019-12-05_21.35.49-server.txt](https://github.com/OpenModularTurretsTeam/OpenModularPassiveDefense/files/3933736/crash-2019-12-05_21.35.49-server.txt)

On a server with 1.12.2 and 139 mods
The conflict is between this mod (OMPD) and Mekanism
It appears to happen on chunk load, though because it is a check for creature spawn I am not 100% sure.
It doesn't matter what Dimension the players base is in, because they have moved it multiple times, and this error keeps appearing randomly.
I have submitted this bug to the Mekanism github as well, which I will link [here](https://github.com/mekanism/Mekanism/issues/5691).

**Comment by Keridos** [comment] 2019-12-07 04:20
Seems to be fixed in Mekanism, closing this.

**Closed as completed by Keridos** 2019-12-07 04:20 UTC

**Comment by CommanderLouiz** [comment] 2019-12-07 04:33
It is not fixed in Mekanism, they just closed the issue saying it isn't their problem.
Despite having [fixed it in the past](https://github.com/mekanism/Mekanism/issues/3663), now it seems they do not want to, which is why I also raised the issue here, hoping one of the sides of the error would know how to resolve it.

**Comment by Keridos** [comment] 2019-12-07 04:37
The issue is on neither of the two sides you mentioned, read the response and the commit in the issue on mekanism. It mentions its a **Sponge** bug and linked this: https://github.com/mekanism/Mekanism/commit/29a3477776dc743d104461aa5d04ccf33732ece9
